MESSAGES = {
    "uz": {
        "start": "🎬 Salom! Men video aniqlash botman.\n\nVideo yuboring, men anime yoki kino nomini topib beraman!",
        "help": "📹 Foydalanish:\n1. Video yuboring (MP4, MOV, AVI)\n2. Men kadrlarni tahlil qilaman\n3. Anime/kino nomini topib beraman\n\n⚙️ Buyruqlar:\n/start - Botni ishga tushirish\n/lang - Tilni o'zgartirish\n/help - Yordma",
        "processing": "⏳ Video qayta ishlanmoqda...\n\n🔍 Kadrlar tahlil qilinmoqda...",
        "found_anime": "🎬 ANIME TOPILDI!",
        "found_movie": "🎬 KINO TOPILDI!",
        "found_series": "📺 SERIAL TOPILDI!",
        "name": "📌 Nomi:",
        "year": "📅 Yili:",
        "genre": "🎭 Janr:",
        "rating": "⭐ Reyting:",
        "description": "📝 Tavsif:",
        "watch_free": "📺 Bepul ko'rish:",
        "watch_paid": "💰 Pullik platformalar:",
        "mal_link": "🔗 MyAnimeList:",
        "tmdb_link": "🔗 TMDB:",
        "not_found": "❌ Topilmadi.\n\nMaslahatlar:\n• Video aniqroq bo'lishi kerak\n• Kamida 2-3 soniya bo'lishi kerak\n• Personajlar ko'rinishi kerak",
        "error": "⚠️ Xatolik yuz berdi. Qaytadan urinib ko'ring.",
        "rate_limit": "⚠️ Kunlik limit tugadi. Ertaga qaytadan urinib ko'ring.",
        "lang_set": "✅ Til o'zgartirildi!",
        "video_too_large": "⚠️ Video juda katta. Maksimal 50MB.",
    },
    "en": {
        "start": "🎬 Hello! I'm a video identification bot.\n\nSend me a video, and I'll find the anime or movie name!",
        "help": "📹 How to use:\n1. Send a video (MP4, MOV, AVI)\n2. I'll analyze the frames\n3. I'll find the anime/movie name\n\n⚙️ Commands:\n/start - Start the bot\n/lang - Change language\n/help - Help",
        "processing": "⏳ Processing video...\n\n🔍 Analyzing frames...",
        "found_anime": "🎬 ANIME FOUND!",
        "found_movie": "🎬 MOVIE FOUND!",
        "found_series": "📺 SERIES FOUND!",
        "name": "📌 Name:",
        "year": "📅 Year:",
        "genre": "🎭 Genre:",
        "rating": "⭐ Rating:",
        "description": "📝 Description:",
        "watch_free": "📺 Watch free:",
        "watch_paid": "💰 Paid platforms:",
        "mal_link": "🔗 MyAnimeList:",
        "tmdb_link": "🔗 TMDB:",
        "not_found": "❌ Not found.\n\nTips:\n• Video should be clearer\n• At least 2-3 seconds long\n• Characters should be visible",
        "error": "⚠️ An error occurred. Please try again.",
        "rate_limit": "⚠️ Daily limit reached. Try again tomorrow.",
        "lang_set": "✅ Language changed!",
        "video_too_large": "⚠️ Video is too large. Maximum 50MB.",
    },
    "ru": {
        "start": "🎬 Привет! Я бот для определения видео.\n\nОтправьте видео, и я найду название аниме или фильма!",
        "help": "📹 Как использовать:\n1. Отправьте видео (MP4, MOV, AVI)\n2. Я проанализирую кадры\n3. Я найду название аниме/фильма\n\n⚙️ Команды:\n/start - Запустить бота\n/lang - Изменить язык\n/help - Помощь",
        "processing": "⏳ Обработка видео...\n\n🔍 Анализ кадров...",
        "found_anime": "🎬 АНИМЕ НАЙДЕНО!",
        "found_movie": "🎬 ФИЛЬМ НАЙДЕН!",
        "found_series": "📺 СЕРИАЛ НАЙДЕН!",
        "name": "📌 Название:",
        "year": "📅 Год:",
        "genre": "🎭 Жанр:",
        "rating": "⭐ Рейтинг:",
        "description": "📝 Описание:",
        "watch_free": "📺 Смотреть бесплатно:",
        "watch_paid": "💰 Платные платформы:",
        "mal_link": "🔗 MyAnimeList:",
        "tmdb_link": "🔗 TMDB:",
        "not_found": "❌ Не найдено.\n\nСоветы:\n• Видео должно быть чётче\n• Минимум 2-3 секунды\n• Персонажи должны быть видны",
        "error": "⚠️ Произошла ошибка. Попробуйте снова.",
        "rate_limit": "⚠️ Дневной лимит исчерпан. Попробуйте завтра.",
        "lang_set": "✅ Язык изменён!",
        "video_too_large": "⚠️ Видео слишком большое. Максимум 50MB.",
    },
    "ja": {
        "start": "🎬 こんにちは！ビデオ識別ボットです。\n\nビデオを送ると、アニメや映画の名前を見つけます！",
        "help": "📹 使い方：\n1. ビデオを送る（MP4、MOV、AVI）\n2. フレームを分析\n3. アニメ/映画の名前を見つける\n\n⚙️ コマンド：\n/start - ボットを起動\n/lang - 言語を変更\n/help - ヘルプ",
        "processing": "⏳ ビデオを処理中...\n\n🔍 フレームを分析中...",
        "found_anime": "🎬 アニメ発見！",
        "found_movie": "🎬 映画発見！",
        "found_series": "📺 シリーズ発見！",
        "name": "📌 名前：",
        "year": "📅 年：",
        "genre": "🎭 ジャンル：",
        "rating": "⭐ 評価：",
        "description": "📝 説明：",
        "watch_free": "📺 見れる場所（無料）：",
        "watch_paid": "💰 有料プラットフォーム：",
        "mal_link": "🔗 MyAnimeList：",
        "tmdb_link": "🔗 TMDB：",
        "not_found": "❌ 見つかりませんでした。\n\nヒント：\n• ビデオはもっと鮮明に\n• 最低2-3秒必要\n• キャラクターが見えること",
        "error": "⚠️ エラーが発生しました。もう一度お試しください。",
        "rate_limit": "⚠️ 日次制限に達しました。明日またお試しください。",
        "lang_set": "✅ 言語が変更されました！",
        "video_too_large": "⚠️ ビデオが大きすぎます。最大50MB。",
    },
}

LANGUAGES = {
    "uz": "🇺🇿 O'zbek",
    "en": "🇬🇧 English",
    "ru": "🇷🇺 Русский",
    "ja": "🇯🇵 日本語",
}


def get_message(lang: str, key: str) -> str:
    return MESSAGES.get(lang, MESSAGES["en"]).get(key, MESSAGES["en"].get(key, ""))
